let entrevista_1 = {
    entrevistador: "Marianna",
    entrevistado: "Emilyn",
    questoes: {
        p1: "Se você pudesse ser um personaguem de filme,livro ou série por um dia, quem seria e por quê?",
        r1: "",
        p2: "Se você pudesse ter um animal de estimação exótico em casa, qual escolheria e por quê?",
        r2: "",
        p3: "Qual é o seu talento secreto ou habilidade inusitada que poucas pessoas conhecem?",
        r3: "",
        p4: "Se você pudesse escolher um mundo de série, filme ou livro para viver, qual seria? Por quê?",
        r4: "",
        p5: "Qual o seu carro dos sonhos?",
        r5: "",
        p6: "Qual era a sua profissão dos sonhos quando você era criança? E por que?",
        r6: "",
        p7: "O que mais sente falta da sua infância?",
        r7: "",
        p8: "Qual o proposito da sua vida?",
        r8: "",
        p9: "Qual profissão você quer seguir? Se tivesse que escolher outra profissão qual seria e por quê?",
        r9: "",
        p10: "Se você tivesse recursos suficientes para estudar em qualquer lugar, qual seria?",
        r10: "",
    }
}

let entrevista_2 = {
    entrevistador: "Verônica",
    entrevistado: "Lucas",
    questoes: {
        p1: "Se você pudesse ser um personaguem de filme,livro ou série por um dia, quem seria e por quê?",
        r1: "",
        p2: "Se você pudesse ter um animal de estimação exótico em casa, qual escolheria e por quê?",
        r2: "",
        p3: "Qual é o seu talento secreto ou habilidade inusitada que poucas pessoas conhecem?",
        r3: "",
        p4: "Se você pudesse escolher um mundo de série, filme ou livro para viver, qual seria? Por quê?",
        r4: "",
        p5: "Qual o seu carro dos sonhos?",
        r5: "",
        p6: "Qual era a sua profissão dos sonhos quando você era criança? E por que?",
        r6: "",
        p7: "O que mais sente falta da sua infância?",
        r7: "",
        p8: "Qual o proposito da sua vida?",
        r8: "",
        p9: "Qual profissão você quer seguir? Se tivesse que escolher outra profissão qual seria e por quê?",
        r9: "",
        p10: "Se você tivesse recursos suficientes para estudar em qualquer lugar, qual seria?",
        r10: "",
    }
}

let entrevista_3 = {
    entrevistador: "Emilyn",
    entrevistado: "Danillo",
    questoes: {
        p1: "Se você pudesse ser um personaguem de filme,livro ou série por um dia, quem seria e por quê?",
        r1: "",
        p2: "Se você pudesse ter um animal de estimação exótico em casa, qual escolheria e por quê?",
        r2: "",
        p3: "Qual é o seu talento secreto ou habilidade inusitada que poucas pessoas conhecem?",
        r3: "",
        p4: "Se você pudesse escolher um mundo de série, filme ou livro para viver, qual seria? Por quê?",
        r4: "",
        p5: "Qual o seu carro dos sonhos?",
        r5: "",
        p6: "Qual era a sua profissão dos sonhos quando você era criança? E por que?",
        r6: "",
        p7: "O que mais sente falta da sua infância?",
        r7: "",
        p8: "Qual o proposito da sua vida?",
        r8: "",
        p9: "Qual profissão você quer seguir? Se tivesse que escolher outra profissão qual seria e por quê?",
        r9: "",
        p10: "Se você tivesse recursos suficientes para estudar em qualquer lugar, qual seria?",
        r10: "",
    }
}

let entrevista_4 = {
    entrevistador: "Danillo",
    entrevistado: "Verônica",
    questoes: {
        p1: "Se você pudesse ser um personaguem de filme,livro ou série por um dia, quem seria e por quê?",
        r1: "",
        p2: "Se você pudesse ter um animal de estimação exótico em casa, qual escolheria e por quê?",
        r2: "",
        p3: "Qual é o seu talento secreto ou habilidade inusitada que poucas pessoas conhecem?",
        r3: "",
        p4: "Se você pudesse escolher um mundo de série, filme ou livro para viver, qual seria? Por quê?",
        r4: "",
        p5: "Qual o seu carro dos sonhos?",
        r5: "",
        p6: "Qual era a sua profissão dos sonhos quando você era criança? E por que?",
        r6: "",
        p7: "O que mais sente falta da sua infância?",
        r7: "",
        p8: "Qual o proposito da sua vida?",
        r8: "",
        p9: "Qual profissão você quer seguir? Se tivesse que escolher outra profissão qual seria e por quê?",
        r9: "",
        p10: "Se você tivesse recursos suficientes para estudar em qualquer lugar, qual seria?",
        r10: "",
    }
}

let entrevista_5 = {
    entrevistador: "Lucas",
    entrevistado: "Marianna",
    questoes: {
        p1: "Se você pudesse ser um personaguem de filme,livro ou série por um dia, quem seria e por quê?",
        r1: "",
        p2: "Se você pudesse ter um animal de estimação exótico em casa, qual escolheria e por quê?",
        r2: "",
        p3: "Qual é o seu talento secreto ou habilidade inusitada que poucas pessoas conhecem?",
        r3: "",
        p4: "Se você pudesse escolher um mundo de série, filme ou livro para viver, qual seria? Por quê?",
        r4: "",
        p5: "Qual o seu carro dos sonhos?",
        r5: "",
        p6: "Qual era a sua profissão dos sonhos quando você era criança? E por que?",
        r6: "",
        p7: "O que mais sente falta da sua infância?",
        r7: "",
        p8: "Qual o proposito da sua vida?",
        r8: "",
        p9: "Qual profissão você quer seguir? Se tivesse que escolher outra profissão qual seria e por quê?",
        r9: "",
        p10: "Se você tivesse recursos suficientes para estudar em qualquer lugar, qual seria?",
        r10: "",
    }
}